// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNWrlrBwIUz0eg7aTB7ZEUOb71kdzuNd4',
    appId: '1:98425329022:web:ff358d921f1f848f928f2f',
    messagingSenderId: '98425329022',
    projectId: 'taskflow-1477b',
    authDomain: 'taskflow-1477b.firebaseapp.com',
    storageBucket: 'taskflow-1477b.firebasestorage.app',
    measurementId: 'G-KT1BWJ9N6T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnSK81-nIB1FelAXNLnh6HMjcFY3Gw2Kw',
    appId: '1:98425329022:android:c5fb8c7282e183e1928f2f',
    messagingSenderId: '98425329022',
    projectId: 'taskflow-1477b',
    storageBucket: 'taskflow-1477b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrq2MRmL4VM96jQGT-YrViVJ8bVBjurqE',
    appId: '1:98425329022:ios:2c14dc7aa38cd6e4928f2f',
    messagingSenderId: '98425329022',
    projectId: 'taskflow-1477b',
    storageBucket: 'taskflow-1477b.firebasestorage.app',
    iosBundleId: 'com.taskflow.taskflowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrq2MRmL4VM96jQGT-YrViVJ8bVBjurqE',
    appId: '1:98425329022:ios:2c14dc7aa38cd6e4928f2f',
    messagingSenderId: '98425329022',
    projectId: 'taskflow-1477b',
    storageBucket: 'taskflow-1477b.firebasestorage.app',
    iosBundleId: 'com.taskflow.taskflowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNWrlrBwIUz0eg7aTB7ZEUOb71kdzuNd4',
    appId: '1:98425329022:web:10b0669fb3c42ef8928f2f',
    messagingSenderId: '98425329022',
    projectId: 'taskflow-1477b',
    authDomain: 'taskflow-1477b.firebaseapp.com',
    storageBucket: 'taskflow-1477b.firebasestorage.app',
    measurementId: 'G-MCVBYHLVXL',
  );
}
